In [8]:
"Factorisation LU pour une matrice tridiagonale"
struct TridiagLU
  lower :: Vector{Float64}
  diag :: Vector{Float64}
  upper :: Vector{Float64}
end

TridiagLU

In [16]:
"Initialisation de la mémoire pour une factorisation n×n"
TridiagLU(n::Int64) = TridiagLU(zeros(n-1), zeros(n), zeros(n-1))
"Dimensions de la matrice représent"
Base.size(A::TridiagLU) = (length(A.diag), length(A.diag))

Base.size

In [17]:
function factorize!(LU::TridiagLU, A::Matrix)
  n = size(A, 1)
  lower, diag, upper = zeros(n-1), zeros(n), zeros(n-1)
  LU.diag[1] = A[1, 1]
  for i in 2:n
    LU.lower[i-1] = A[i, i-1] / LU.diag[i-1]
    LU.upper[i-1] = A[i-1, i]
    LU.diag[i] = A[i, i] - LU.lower[i-1] * LU.upper[i-1]
  end
  return LU
 end

factorize! (generic function with 1 method)

In [18]:
A = Float64[2 -1 0 0;
            -1 2 -1 0;
            0 -1 2 -1;
            0 0 -1 2 ]

LU = TridiagLU(4)
factorize!(LU, A)
display(LU.lower)
display(LU.diag)
display(LU.upper)

3-element Vector{Float64}:
 -0.5
 -0.6666666666666666
 -0.7499999999999999

4-element Vector{Float64}:
 2.0
 1.5
 1.3333333333333335
 1.25

3-element Vector{Float64}:
 -1.0
 -1.0
 -1.0

In [19]:
function TridiagLU(A::Matrix)
  LU = TridiagLU(size(A, 1)) # on initialise la mémoire
  factorize!(LU, A) # on effectue la factorisation
 end

TridiagLU